export const REQUEST_MADE = 'REQUEST_MADE';
export const RESPONSE_RECEIVED = 'RESPONSE_RECEIVED';

export const GALLERY_PHOTOS_REQUEST = 'GALLERY_PHOTOS_REQUEST';
export const GALLERY_PHOTOS_REQUEST_SUCCESS = 'GALLERY_PHOTOS_REQUEST_SUCCESS';
export const GALLERY_PHOTOS_REQUEST_FAILURE = 'GALLERY_PHOTOS_REQUEST_FAILURE';
export const GALLERY_PHOTOS_FILTER = 'GALLERY_PHOTOS_FILTER';
